name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: kkoor521/royal-flash
          stage: main
          yaml: >
            name: royal-flash-react

            app: web

            options:
              nodeversion: "16"
              docbase: /dist
              build: npm run build
              spa: true
              buildenv:
                - name: VITE_BASE_URL
                  value: ${{ secrets.VITE_BASE_URL }}
              indexpage: index.html
              install: npm i
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
